### ISSUE TITLE
Allow output to file without a connection string

### ISSUE THREAD

**Issue by worldspawn** [schambers/fluentmigrator#269]
I have been playing with the output option of the console runner and noticed that I can output to file but I still need to have a working connection string - and the script is then executed against that connection. At the moment the output option feels more like a logging feature rather than something functional.

In some cases it might be required to generate a script to be run later/independently (like when the hosting environment is not accessible from CI or the dev team). That script should include every migration (or up to the specified version) and wrap each of the migrations in an inline check against the versioninfo table to see if it actually needed to be run.

**Comment by andrewhanson** [comment]
Just ran into this same issue on a current project and created a pull request for supporting connectionless migrations.  
https://github.com/schambers/fluentmigrator/pull/570

 I didn't add any version checking into the output yet but now that the connection is pulled out it would probably be easier to extend.

I'd be interested in your thoughts/comments if you still have this issue.
