### ISSUE TITLE
Running migration from within application

### ISSUE THREAD

**Issue by dealproc** [schambers/fluentmigrator#314]
Can we obtain a wiki page for how to run migrations from within an application?  Would like to also know if there's a way of issuing a backup/restore process through FluentMigrator as well... I seem to be having need for these features/functionality.
...
If we could get this to trigger within a Web Deployment package for web projects, that would work, but I still need it for thick client applications.

**Comment by karaaie** [comment]
+1, I have a similar usecase

**Comment by dealproc** [comment]
I'm also using this now with Octopus Deploy, and am running migrations on sql servers during deployments of new versions of our website(s).

If I haven't posted the bits, let me know how i can create a project for this (like if we can establish a "group" in github) and I'll put the bits in place so others can use it.

**Comment by karaaie** [comment]
I'd be very keen on seeing what you have pieced together. Perhaps you can make a simple project in your own account and link it here? Perhaps even send a PR to @schambers with a notice on the readme with the link to your sample? :)

**Comment by dealproc** [comment]
nupackage with a 1-line powershell script that runs the console runner was about all it was.

**Comment by dealproc** [comment]
This is about all it took to make it happen:
https://gist.github.com/dealproc/0077c04de71627d8929f
