### ISSUE TITLE
Add support for provider specific options

### ISSUE THREAD

**Issue by hazzik** [schambers/fluentmigrator#367]
It would be useful to have provider specific run options, for example `-oracle:case-insensitivity`.

**Comment by tommarien** [comment]
@hazzik i guess it's already there see -providerswitches=QUOTEDIDENTIFIERS=TRUE for instance on oracle to quote identifiers, needs documentation on the wiki though

**Comment by tommarien** [comment]
@hazzik i've added the switch to the wiki see https://github.com/schambers/fluentmigrator/wiki/Command-Line-Runner-Options
