### ISSUE TITLE
Implement SystemMethod CurrentDateTime For Oracle

### ISSUE THREAD

**Issue by daniellee** [schambers/fluentmigrator#370]
In #170, there is a change implementing the CurrentDateTime (see https://github.com/wilbit/fluentmigrator/blob/61b35cf82ef9208ddc268120448eb95e93c6d491/src/FluentMigrator.Runner/Generators/Oracle/OracleColumn.cs#L60-61).

This change would need to be integration tested against an Oracle db and unit tests written as well.

**Comment by tommarien** [comment]
Fixed by https://github.com/schambers/fluentmigrator/pull/478
