### ISSUE TITLE
SQL CE + chaining Insert.IntoTable().Row() calls

### ISSUE THREAD

**Issue by stonkie** [schambers/fluentmigrator#421]
Chaining insert row calls doesn't work on SQL server CE because the resulting SQL is a single query separated by semi-colons which is not supported by SQL Server CE.

For example, this doesn't work :

Insert.IntoTable("TableName")
        .Row(new { SomeColumn = "test1" })
        .Row(new { SomeColumn = "test2" });

But this does :

Insert.IntoTable("TableName").Row(new { SomeColumn = "test1" });
Insert.IntoTable("TableName").Row(new { SomeColumn = "test2" });

The right way to do this in SQL Server CE seems to use UNION ALL as described here : http://forums.asp.net/t/1751896.aspx/1

I could override the Generate(InsertDataExpression) on the SqlServerCeGenerator to write this in valid SQL Server CE syntax. Is anyone else working on this right now or was it fixed in another branch?

**Comment by tommarien** [comment]
@stonkie I guess nobody is working on it atm, if you could provide a pull that would be amazing ;)

**Comment by stonkie** [comment]
We did some prototyping but we never actually supported SQL Server CE. We wanted to use it for isolated automated integration tests but it turns out it caused more problems than it solved. I never got to implement this before we dropped the feature. Sorry...

**Comment by tommarien** [comment]
Closed by merge
