### ISSUE TITLE
Decimal size and precision parameter values are used inversly

### ISSUE THREAD

**Issue by jamiehinton** [schambers/fluentmigrator#440]
When adding a decimal field to an existing table I found that the size and precision parameters whilst the correct way around in the parenthesis when running the migration against SQL server caused an issue that stated that the size (scale) for the new column was incorrect.

As an example:
Create.Column( "GreatColumn" ).OnTable( "SuperTable" ).AsDecimal( 2, 5 ); fails but
Create.Column( "GreatColumn" ).OnTable( "SuperTable" ).AsDecimal( 5, 2 ); is fine.

Happy to fork and fix if it is an issue :)

**Comment by tommarien** [comment]
Closed by #596  for firebird ;)
