### ISSUE TITLE
Postgres -of -p command does not generate semicolons after Update/Create statements

### ISSUE THREAD

**Issue by joellhill** [schambers/fluentmigrator#446]
We have need to use the sql generated by fluentmigrator for other purposes but the -preview command does not generate ';' after Create/Update/Alter statements.  It does generate correctly after INSERT statements.

Script fails if using the output .sql file.  See attachment for example.

![invalidsemicoloninpreview](https://f.cloud.github.com/assets/3099407/1123432/17793fd2-1aef-11e3-897d-07770581327b.png)

**Comment by tommarien** [comment]
Closed by merge
