### ISSUE TITLE
Bug fix: Prevent SQLServer identity columns getting a 'default' constraint

### ISSUE THREAD

**Issue by tohagan** [schambers/fluentmigrator#465]
Creating tables with an Identity column cause a SQL Server error as they assign a default value:

    Create.Table("tblAdmAnalysisCode").InSchema("dbo")
	.WithColumn("fldAnalysisCodeID").AsInt32().NotNullable().PrimaryKey().Identity()
	.WithColumn("fldAnalysisCodeCode").AsString(50).Nullable().Indexed()

Emits SQL:

    CREATE TABLE [dbo].[tblAdmAnalysisCode] 
    ([fldAnalysisCodeID] INT NOT NULL CONSTRAINT [DF_tblAdmAnalysisCode_fldAnalysisCodeID] DEFAULT NULL IDENTITY(1,1), 
     [fldAnalysisCodeCode] NVARCHAR(50) CONSTRAINT  [DF_tblAdmAnalysisCode_fldAnalysisCodeCode] DEFAULT NULL, 
     CONSTRAINT [PK_tblAdmAnalysisCode] PRIMARY KEY ([fldAnalysisCodeID]))

That causes the error: **Defaults cannot be created on columns with an IDENTITY attribute**

**FIX**: Added check for column.IsIdentity in SqlServerColumn.cs to prevent default being set.

        protected override string FormatDefaultValue(ColumnDefinition column)
        {
            if (!column.IsIdentity)
            {
                if (DefaultValueIsSqlFunction(column.DefaultValue))
                    return "DEFAULT " + column.DefaultValue.ToString();

                var defaultValue = base.FormatDefaultValue(column);

                if (column.ModificationType == ColumnModificationType.Create && !string.IsNullOrEmpty(defaultValue))
                    return "CONSTRAINT " + Quoter.QuoteConstraintName(GetDefaultConstraintName(column.TableName, column.Name)) + " " + defaultValue;
            }

            return string.Empty;
        }

**Comment by tohagan** [comment]
Oops. Sorry I failed to reply on this one.  Was a long time ago.

**Comment by tommarien** [comment]
@tohagan If this is still an issue i can reopen it, if you provide more context ;)
