### ISSUE TITLE
SqlAzure does not support sys.sp_addextendedproperty

### ISSUE THREAD

**Issue by colinangusmackay** [schambers/fluentmigrator#513]
A SQL Azure database does not support a number of things that are available in SQL Server 2012, such as sys.sp_addextendedproperty which means that WithColumnDescription() fails when applied to a SQL Azure database, although it works perfectly fine when applied to a SQL Server 2012 database.

**Comment by tommarien** [comment]
I'll close this issue because not enough reasons to create a sqlazure provider atm
