### ISSUE TITLE
MySQL: AsString yields TEXT not VARCHAR

### ISSUE THREAD

**Issue by mwpowellhtx** [schambers/fluentmigrator#517]
Hello,

I want to produce a VARCHAR column in MySQL, not TEXT.

Short of AsCustom, is there a way to teach FluentMigrator that the convention should be VARCHAR(n) and not TEXT?

Thank you...

**Comment by RobPethick** [comment]
@tommarien Can I assume we want to adjust both DbType.AnsiString and DbType.String to take 65535 as max value?

**Comment by RobPethick** [comment]
Actually I'll wait on #681 as it looks like there could be some merge conflicts
