### ISSUE TITLE
How to specify an index for multiple foreign keys

### ISSUE THREAD

**Issue by mwpowellhtx** [schambers/fluentmigrator#523]
I've got a table, in loose pseudo SQL:

```SQL
CREATE TABLE Leagues (Id, Name);

CREATE TABLE Scoring (Id, ...);

CREATE TABLE LeagueScoring (Id,
    LeagueId REFERENCES Leagues.Id ON DELETE CASCADE ON UPDATE CASCADE,
    ScoringId REFERENCES Scoring.Id ON DELETE CASCADE ON UPDATE CASCADE);
```

However, I am getting SQL errors on the current migration I am working on. The LeagueScoring table is being created, and the first FK is created. But the second one is not.

I believe the issue to be something about the table needs an index to include (Id, LeagueId, ScoringId), that constitutes a LeagueScoring entry, which it basically does.

BTW, would be great if somehow the generated SQL, or some hint about it, was provided as well as the immediate thrown exception, but that's a separate issue I think.

So, how to specify an index when creating tables upon migration?

**Comment by tommarien** [comment]
@mwpowellhtx No clue what you are trying to say here, what is the underlying problem and the migrations you are using ?

**Comment by tommarien** [comment]
Closed, no response
