### ISSUE TITLE
Alter table for SQLite

### ISSUE THREAD

**Issue by kayone** [schambers/fluentmigrator#525]
A member of our project @Taloth recently implemented alter logic for SQLite using temporary tables. I was wondering if we clean it up and would you consider accepting it as pull request?

the reason I ask is because it uses temporary tables which feels a bit hacky but we need it and I'm sure other people do too.

https://github.com/NzbDrone/NzbDrone/pull/104/files

**Comment by dealproc** [comment]
:+1: This would be really great to have something like this.  I dislike the concept that I am having to create a specific set of migrations for SQLite as compared to other RDBMSes.

**Comment by kayone** [comment]
@dealproc to be honest I don't think this will happen since there has been no replies from the fluent-migrator maintainers, I don't think I would invest any time or effort in a pull-request that won't likely be merged. But feel free to take the code from our project as import it into yours.

**Comment by tommarien** [comment]
@kayone if you could create a pull for this feature, we would be happy to pull it in. Sorry for the lack of reaction

**Comment by dealproc** [comment]
*bump*

@kayone - Any progress?  It's something that is quite interesting to have in.
