### ISSUE TITLE
System.BadImageFormatException assembly 'FluentMigrator.Runner'

### ISSUE THREAD

**Issue by mwpowellhtx** [schambers/fluentmigrator#528]
I installed from Nuget. I am testing our adoption of Runner in a test assembly through NUnit. When I attempt to run the unit test, which subsequently loads the assembly for the dependency, we get the following exception.

<pre>
System.BadImageFormatException : Could not load file or assembly 'FluentMigrator.Runner, Version=1.3.0.0, Culture=neutral, PublicKeyToken=aacfc7de5acabf05' or one of its dependencies. An attempt was made to load a program with an incorrect format.
</pre>

On the surface, one workaround would be to target the x86 platform in the unit tests. However, a better long term answer IMO, if possibly, would be for Runner to include an x64 version.

**Comment by tommarien** [comment]
@mwpowellhtx either close the issue or give more context please

**Comment by mwpowellhtx** [comment]
not to say it's still not an FM issue still. I've long since moved on, however. rolled my own image-compatible migrations. thank you...
