### ISSUE TITLE
Use only DSL to generate SQL

### ISSUE THREAD

**Issue by bertvan** [schambers/fluentmigrator#532]
Hi,

Is it possible to use only the "SQL DSL" to generate sql scripts with Fluentmigrator? Or are there any other libraries which allow this?

**Comment by tommarien** [comment]
@bertvan If you just want to run scripts, you could use Execute.Script or Execute.EmbeddedScript

**Comment by bertvan** [comment]
Hi, it's been a while, and I can't really remember why I wanted this... But, I know (knew) acout Execute.Script, so that wasn't it.
I think, I wanted to have access to the actual SQL that is generated by FluentMigrator.

**Comment by tommarien** [comment]
@bertvan You could do that by using the --preview and --output switches

**Comment by bertvan** [comment]
OK thanks!
