### ISSUE TITLE
Add custom VersionInfo Column

### ISSUE THREAD

**Issue by jbattermann** [schambers/fluentmigrator#563]
Good evening,

is it possible to extend the default VersionInfo table with an additional column that is being filled during migrations? And/or can I set a migration's description during run-time?

I am wondering because what I'd like to do is to add a 'deployment id' to the persisted migration / versioninfo so I can associate specific deployments to a particular (set of) migrations.

Thanks,
-J

**Comment by tommarien** [comment]
@jbattermann see MigrationAttribute overload with description, does that fulfill the need ?

**Comment by jbattermann** [comment]
Ahhh - Yep that's perfectly fine for me. Thanks @tommarien !

**Comment by tommarien** [comment]
@jbattermann no problem ;)
