### ISSUE TITLE
Fluent Migration not Work

### ISSUE THREAD

**Issue by hoodam** [schambers/fluentmigrator#567]
i installed the fluentmigrator version 1.4 and then run the command and give me the task completed successfully but no update to database happened while the same migration done before on version 1.3 

i changed the name of the version table but it creates the default name 
it ignores all other migration classes

**Comment by tommarien** [comment]
Could you give us a little bit more context like which db which migratation. Try to give as much as possible

**Comment by hoodam** [comment]
Dear sir,

please find the following code

using FluentMigrator;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using TestAngularJS.TaskModule;

namespace TestAngularJS.DbMigrations
{
    [Migration(1)]
    public class _01_CreatePersonTable:Migration
    {
        public override void Up()
        {
            string tableName = "tajPerson";
            Create.Table(tableName).

WithColumn("Id").AsInt32().Identity().PrimaryKey().NotNullable().
                WithColumn("Name").AsString(32).NotNullable();

            Insert.IntoTable(tableName).
                Row(new  { Name = "Ahmed" }).
                Row(new  { Name="Ali"});
        }
        public override void Down()
        {

        }

    }

}
------------------------------------------------------------------------------------------------------

using FluentMigrator.VersionTableInfo;

namespace TestAngularJS.DbMigrations
{
    [VersionTableMetaData]
    public class VersionTable : DefaultVersionTableMetaData
    {
        public override string TableName
        {
            get
            {
                return "tajVersionInfo";
            }
        }
    }
}
---------------------------------------------------------------------------------------------------------------------

now i run this command after build the application
Migrate.exe  /connection "Server=localhost; Database=TestAngularJSDB1;
Trusted_Connection=True;" /db sqlserver /a
"bin\Debug\TestAngularJS3.NHibernate.dll"

and i got the following

-------------------------------------------------------------------------------
=============================== FluentMigrator
================================
-------------------------------------------------------------------------------
Source Code:
  http://github.com/schambers/fluentmigrator
Ask For Help:
  http://groups.google.com/group/fluentmigrator-google-group
-------------------------------------------------------------------------------
[+] Using Database sqlserver and Connection String Server=localhost;
Database=Te
stAngularJSDB1; Trusted_Connection=True;
[+] Task completed.



what i found in database is the default version Table name[VersionInfo] not
[tajVersionInfo]

no other tables are created



i was wonder if there are a logging methodology to trace the fluent
migrator steps to find the error

thank you
Mahmoud Slama

**Comment by tommarien** [comment]
@hoodam i just tried your exact setup locally on my machine with latest nuget no problems here, everything is created first time as expected, if i run it a second time i got same output as you but that is normal behavior.

Could you try using a new database and see if it works there. You could try the verbose option but i guess that will not get you any further.

Kr

**Comment by hoodam** [comment]
This is what I did before I retried on new database I am also using
boilerplate FYI
Thank you
Mahmoud slama

**Comment by modesto** [comment]
¿Do you have Fluent Migrator Tools 1.3.x folder in your PATH environment variable? 

If you execute migrate.exe from Fluent Migrator Tools 1.3 in a project that use Fluent Migrator 1.4, you will have this symptoms.

**Comment by tommarien** [comment]
@hoodam any update on this issue ?

**Comment by hoodam** [comment]
I think the problem with the boilerplate asp.net as the downloaded package
has the old version of fluent migration and nuget get the latest version of
it which means I have a package folder with the two versions and this leads
us to the scenario you mentioned before

But as I think if I have 2 versions of the same project should not make a
problem

Thank you

**Comment by tommarien** [comment]
I'll consider this as a closed issue as of now ;)
