### ISSUE TITLE
ASP.NET Runner

### ISSUE THREAD

**Issue by giggio** [schambers/fluentmigrator#584]
I have build an ASP.NET Runner. It is here: https://github.com/giggio/FluentMigrator.Runner.Aspnet
Feel free to integrate the code back into your repo if you would like to. In this case I will then remove my project. If you prefer a PR, please tell me how you prefer it (directory, names, etc).
It is not a full implementation yet, but it works.

**Comment by tommarien** [comment]
@giggio looks great, for the moment i would like to keep as a community package as it is atm, maybe when we ever get an agreement on the fluent runner we could more tightly integrate ;) anyway thanks for the announcement

**Comment by tommarien** [comment]
@giggio i am going to keep this issue open as one-to-watch
