### ISSUE TITLE
Migrate.exe --help doesn't work correctly

### ISSUE THREAD

**Issue by NetworKKnighT** [schambers/fluentmigrator#600]
Migrate.exe --help doesn't work correctly, because DisplayHelp method throws ArgumentOutOfRangeException while processing "noConnection" option.
This occurs in [line 258](https://github.com/schambers/fluentmigrator/blob/master/src/FluentMigrator.Console/MigratorConsole.cs#L258) of MigratorConsole.cs. As I understand OptionSet.WriteOptionDescriptions method throws the exception when length of Option.Description is 134.

**Comment by tommarien** [comment]
@NetworKKnighT Thanks will try to fix asap, issue with optionset object

**Comment by tommarien** [comment]
@NetworKKnighT Doh, i already assigned myself to this bug, have everything ready for the pull request :S
