### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by tommarien** [schambers/fluentmigrator#601]
I yesterday did a small update on the readme.textile to add a nuget badge. Apparantly the travis build failed on 

The command "sudo apt-get install mono-devel mono-gmcs nunit-console libfbembed2.5" failed and exited with 100 during .

I reference whitelist request https://github.com/travis-ci/travis-ci/issues/3641

**Comment by katlimruiz** [comment]
+1

**Comment by tommarien** [comment]
Anyone that can help me with this, i have not clue what to do anymore, i think main stuff we use is whitelisted (Darn travis :) )
