### ISSUE TITLE
Maintenance class without tags is not executed (it should)

### ISSUE THREAD

**Issue by katlimruiz** [schambers/fluentmigrator#606]
Hi

I'm using SqlAzure and the collation at db level cannot be changed. Therefore I need to set collation for each column individually.

So there are two possibilities: either do a post up action so every migration that I make can run a query to validate whether all string columns have the correct collation, or to allow to set the collation while creating or altering the column.

I will try to do a pull request for this, but can't promise as it will take me time to do it.

Thanks

**Comment by katlimruiz** [comment]
I just saw the Maintenance attribute, but seems to not work the way I would want.

I put Maintenance(AfterAll) and it doesnt run the migration class.

I put the Migration(0) and it doesnt work either.

I dont want to put Migration(99999) as I believe it would screw up the VersionInfo table.

Other option?

**Comment by katlimruiz** [comment]
Ok, I got working my Maintenance(AfterAll) class. It only works if I specify a TAG and use it in the runner.

Shouldn't this be an issue?

The correct flow should be:
1. If the runner specifies a tag, only those migrations with the tag are done.
2. But if the runner does not specify a tag, all migrations should be done including the maintenance.

So I will change the subject :smile:

**Comment by tommarien** [comment]
Closed by merge
