### ISSUE TITLE
The project will not complete

### ISSUE THREAD

**Issue by MohammedAl-Qaisi** [schambers/fluentmigrator#609]
There is no enough documentation ... with the time that i wasted in fixing the error ( Could not load file or assembly 'FluentMigrator, Version=1.3.0.0) . i can go to the moon and return with ice-cream...

that so bad...

**Comment by tommarien** [comment]
@MohammedAl-Qaisi Thanks for this issue, we are aware that we are lacking documentation here and there. I can only encourage more wiki pull requests coming ;)

**Comment by MohammedAl-Qaisi** [comment]
I'm sorry for that , but i see a fantastic project &  lacking documentation... good luck

**Comment by tommarien** [comment]
@MohammedAl-Qaisi Could you give a few pointers to where the documentation is definitly missing for ?

**Comment by tommarien** [comment]
I'll consider this issue as closed until i get some clear point of where documentation is missing.
