### ISSUE TITLE
Oracle TypeMap must allow up to 4000 characters in VARCHAR2 / NVARCHAR2 fields

### ISSUE THREAD

**Issue by jonnybee** [schambers/fluentmigrator#612]
see: [http://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT1822](http://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT1828) 

*The VARCHAR2 datatype stores variable-length character strings. When you create a table with a VARCHAR2 column, you specify a maximum string length (in bytes or characters) between 1 and 4000 bytes for the VARCHAR2 column*

FluentMigrator has a limit of 2000 characters and if above will create a CLOB column. The limit should be altered to allow up to 4000 characters.

The same goes for NVARCHAR2 fields. 
*The maximum length of an NVARCHAR2 column is 4000 bytes. It can hold up to 4000 characters. The actual data is subject to the maximum byte limit of 4000.*

I can submit PR if you will accept!

**Comment by tommarien** [comment]
Closed by #613
