### ISSUE TITLE
SqlServerCe: Alter column to nullable does not work

### ISSUE THREAD

**Issue by tommarien** [schambers/fluentmigrator#616]
* Case:
  A column that is defined as not null
* Alter.Column("blah").OnTable("balh").AsString(120).Nullable()

**Comment by mstancombe** [comment]
I'll check this out of noone else is.

**Comment by tommarien** [comment]
@mstancombe thanks ;)

**Comment by tommarien** [comment]
Weirdly enough : we are using SqlserverColumn

So in sqlserver ALTER COLUMN XXX VARCHAR(20) changes from notnull to nullable

When using same statement in Sqlserverce does not do anything, you have to specify 
ALTER COLUMN XXX VARCHAR(20) **NULL** to change it

Can not find any documentation on it
