### ISSUE TITLE
SqlServerCe: Typemap is wrong

### ISSUE THREAD

**Issue by tommarien** [schambers/fluentmigrator#618]
see https://technet.microsoft.com/en-us/library/ms172424%28v=sql.110%29.aspx

* VARCHAR AND CHAR are not supported only NVARCHAR AND NCHAR
* TEXT is not support, NTEXT is up until 536,870,911 characters
* VARBINARY(max) is not supported

**Comment by eloekset** [comment]
I've sent pull request #681

**Comment by fubar-coder** [comment]
Resolved
