### ISSUE TITLE
Use semver

### ISSUE THREAD

**Issue by giggio** [schambers/fluentmigrator#623]
Right now the nuget file for `FluentMigrator` and `FluentMigrator.Runner` are using 4 numbers to define their version number. [Semver](http://semver.org/) does not use this 4th position, it stops at the third one. This is causing issues with `dnx` (see https://github.com/aspnet/dnx/issues/2192).
Please post a new version without the 4th version number, as `1.5.2` to both packages, which will respect semver's versioning scheme.

**Comment by tommarien** [comment]
@giggio I'll make sure that 1.6.0 uses semver ;)

**Comment by giggio** [comment]
@tommarien Excelent! Would you know when is 1.6.0 expected?

**Comment by tommarien** [comment]
Within a couple days ( max next week )
