### ISSUE TITLE
Issue with running MSBuild Migrate task from within Visual Studio

### ISSUE THREAD

**Issue by zendever** [schambers/fluentmigrator#627]
I believe this problem may be related to this closed issue:

https://github.com/schambers/fluentmigrator/issues/425

When trying to run the Migrate MSBuild custom task from within visual studio (i.e. running the build command on a migration project that targets the Migrate task), MSBuild will lock the migration DLL passed to the Migrate task. This prevents the developer from cleaning and/or rebuilding the project until the rogue MSBuild process unloads itself.

The cause is that when Visual Studio runs the build, any assemblies loaded via reflection are loaded into the primary AppDomain for the MSBuild process, and Visual Studio manages the recycling of that process.

We can get around this by having the Migrate task inherit from AppDomainIsolatedTask (or creating a different task that does so).

I tested this out on a local build and it works perfectly fine.

**Comment by tommarien** [comment]
@zendever I see no problem in inheriting from AppDomainIsolatedTask, do you mind creating a pull for it ?

**Comment by tommarien** [comment]
Closed by merging #629
