### ISSUE TITLE
Using Fluent Migrator to Select from Database

### ISSUE THREAD

**Issue by jogibear9988** [schambers/fluentmigrator#633]
Are there any commands to Query/Select Data from a Database? Is this Planed? 

If not, if I work on this will a Pull Req for such functionality accepted?

**Comment by tommarien** [comment]
Execute.WithConnection is available

**Comment by jogibear9988** [comment]
I know, but in this I have to use SQL. I want a Fluent Syntax, is this possible? Or will this be accepted?

**Comment by tommarien** [comment]
@jogibear9988 It might be a little tricky to get it handled by all providers but if it's good, it will be accepted :)

**Comment by jogibear9988** [comment]
I've started with a little bit of Code.
Maybe someone can look at it!

I started with Sqlite atm.

https://github.com/jogibear9988/fluentmigrator/commit/6978ce5310c1720973811069e2748df35866b40e

**Comment by jogibear9988** [comment]
I've included my changes in a Pull Req, wich is not yet finished...

https://github.com/schambers/fluentmigrator/pull/634/files
