### ISSUE TITLE
Why am I unable to create table structure

### ISSUE THREAD

**Issue by MetSystem** [schambers/fluentmigrator#639]
hello
I can't transfer.
version 1.5.1.0
```cs
[Migration(1)]
    public class CreateUser : Migration
    {
        public override void Down()
        {
            Create.Table("User")
               .WithColumn("Id").AsGuid().PrimaryKey().WithDefault(SystemMethods.NewGuid)
               .WithColumn("Version").AsInt32().NotNullable().WithDefaultValue(0);

        }

        public override void Up()
        {
            //Delete.Table("Users");
        }
    }

```

**Comment by jtreuting** [comment]
You are going to need to provide some more information.  What error are you getting?  What database is this running against?

**Comment by stefan-ojog** [comment]
It seems you're creating the table on the Down method and deleting it on the Up method. It should be the other way around.

**Comment by MetSystem** [comment]
I've used EF have solved the problem of connecting the oracle.
Thank you very much.
