### ISSUE TITLE
Oracle: Improper Currency precision

### ISSUE THREAD

**Issue by jarz** [schambers/fluentmigrator#645]
FluentMigrator currently creates a NUMBER(19, 1) column. According to [Oracle](https://docs.oracle.com/cd/B19306_01/gateways.102/b14270/apa.htm), the SQL Server equivalent of MONEY is NUMBER(19,4).

At the very least, the decimal precision should be bumped to two. Otherwise we're rounding to the nearest tenth on insert and update operations.

**Comment by tommarien** [comment]
Closed by merge
