### ISSUE TITLE
Oracle: Error when using single quote character ( ' ) as argument for WithDescription(string) method.

### ISSUE THREAD

**Issue by barser** [schambers/fluentmigrator#650]
Oracle: Error when using single quote character ( ' ) as argument for WithDescription(string) method.

Please consider adding checks into OracleDescriptionGenerator.GenerateColumnDescription/GenerateTableDescription methods.

**Comment by barser** [comment]
SELECT 'test single quote'||CHR(39) from dual;
SELECT q'[test single quote']' from dual;
SELECT '''' from dual;

**Comment by fubar-coder** [comment]
PR merged
