### ISSUE TITLE
Include terminals in output file

### ISSUE THREAD

**Issue by coldacid** [schambers/fluentmigrator#669]
For databases that require them (i.e. PostgreSQL), generated SQL output files should include the statement terminal character so that the generated script can be run on its own. Currently the files generated only include the terminal for VersionInfo table inserts at the end of each migration.

**Comment by tommarien** [comment]
@coldacid Hi Chris

Related to #446 (will probably be fixed in 1.6.1)

KR

**Comment by coldacid** [comment]
Any idea on when 1.6.1 will be out?
