### ISSUE TITLE
Support for Pre/Post Deploy scripts or actions

### ISSUE THREAD

**Issue by limitzero** [schambers/fluentmigrator#694]
Just an idea to have pre and post deploy migration actions that should run when before starting the migration and after the migration(s) have successfully finished. The runner could pick these up like regular migrations..

**Comment by tommarien** [comment]
Like the maintenance attribute you mean ?

Verstuurd vanaf mijn iPhone

**Comment by barser** [comment]
You can use Profiles as post deploy scripts

**Comment by limitzero** [comment]
Is there a sequence as to when the profiles run? Do they occur before the Migration/ForwardMigration actions?

**Comment by barser** [comment]
They are called after all migrations

**Comment by limitzero** [comment]
Thanks
