### ISSUE TITLE
NullReferenceException in Fluent.Runner.TypeFinder if class has no namespace

### ISSUE THREAD

**Issue by barser** [schambers/fluentmigrator#698]
NullReferenceException in Fluent.Runner.TypeFinder if any class in project has no namespace.

**Comment by RenaldSB** [comment]
Hi,
How do you call "FilterByNamespace" method?

**Comment by barser** [comment]
Sorry, I',ve found that this bug is already fixed in 1.6.1 - https://github.com/schambers/fluentmigrator/commit/9ffa3fe9bcbe9bd48c1673703da56a9b61335de2
