### ISSUE TITLE
Can I use FluentMigrator with .NET Core?

### ISSUE THREAD

**Issue by olafleur** [schambers/fluentmigrator#778]
If not, is this support planned ?

**Comment by fubar-coder** [comment]
It's not supported yet, but support is definitely planned.

**Comment by eloekset** [comment]
@olafleur follow #712

**Comment by reinaldocoelho** [comment]
I think we can close this issue and maintain discussion in the #712, right?

**Comment by fubar-coder** [comment]
Closed as duplicate of #712

**Comment by olafleur** [comment]
Thanks a lot !
